call class serialize/deserialize methods
near/borsh-js pull request #20
Opened 2021-05-20 13:18 UTC by mehtaphysical

Fixes #19

2021-05-21 22:02 UTC, ailisp commented on package.json
> +    "bn.js": "^5.2.0",
nice cleanup!

2021-05-21 22:05 UTC, ailisp commented on lib/index.js
> +        obj.serialize(writer);
I would prefer obj.borshSerialize/obj.borshDeserialize for a less chance of name collision

2021-05-21 22:07 UTC, ailisp approved these changes
Code change looks good to me, @volovyk-s do you think the API change makes sense?

2021-05-25 17:11 UTC, volovyk-s requested changes
Looks good overall. Let's add simple unit tests and merge this PR.

2021-05-27 14:25 UTC, volovyk-s approved these changes

2021-05-27 15:51 UTC, merged